#Server
# source: "site"
source: ./web-school-lectures/site
baseurl: /web-school-lectures
includes_dir: /web-school-lectures/_includes
exclude: [assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, README.md]

#Social
title: Web School Lectures
description: "Social UI"
authors: PavelGalanin2001
