# Jekyll
exclude:
  - assets
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md

# Varibles
title: Web School Lectures
description: Social UI
authors: PavelGalanin2001
