# Jekyll
baseurl: '/jekyll-social-ui'
exclude:
  - node_modules
  - src
  - gulpfile.js
  - package-lock.json
  - package.json
  - README.md

# Varibles
title: Social UI
description: ...
authors: PavelGalanin2001
